# Устанавливаем базовый образ Node.js
FROM node:20.18.3

# Устанавливаем рабочую директорию
WORKDIR /usr/src/app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем все остальные файлы приложения
COPY . .

# Скомпилируем TypeScript в JavaScript
RUN npm run build

EXPOSE 3000

# Запускаем приложение
CMD ["npm", "run", "start:prod"]


