networks:
  out-net:
    driver: bridge
  into-net:
    driver: bridge 

services:
  user-db:
    image: postgres:16
    container_name: db-user
    env_file:
      ./.env.user
    ports:
      -  "${POSTGRES_PORT}:5432"
    networks:
      - into-net

  todo-db:
    image: postgres:16
    container_name: todo-db
    env_file:
      ./.env.todo
    ports:
      -  "${POSTGRES_PORT}:5432"
    networks:
      - into-net

  push-db:
    image: postgres:16
    container_name: push-db
    env_file:
      ./.env.push
    ports:
      -  "${POSTGRES_PORT}:5432"
    networks:
      - into-net

  auth-db:
    image: postgres:16
    container_name: auth-db
    env_file:
      ./.env.auth
    ports:
      -  "${POSTGRES_PORT}:5432"
    networks:
      - into-net

  redis-session:
    image: redis:7
    container_name: redis-sessions
    restart: always
    env_file: ./.env.redis.sessions
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "8001:8001"
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  redis-data:
