networks:
  out-net:
    driver: bridge
  into-net:
    driver: bridge 

services:
  user-db:
    image: postgres:16
    container_name: db-user
    env_file:
      ./.env.user
    ports:
      -  "5432:5432"
    networks:
      - into-net

  todo-db:
    image: postgres:16
    container_name: todo-db
    env_file:
      ./.env.todo
    ports:
      -  "${POSTGRES_PORT}:5432"
    networks:
      - into-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  push-db:
    image: postgres:16
    container_name: push-db
    env_file:
      ./.env.push
    ports:
      -  "${POSTGRES_PORT}:5432"
    networks:
      - into-net

  auth-db:
    image: postgres:16
    container_name: auth-db
    env_file: 
      ./.env.auth
    ports:
      -  "5432:5432"
    networks:
      - into-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis-session:
    image: redis:7
    container_name: redis-sessions
    restart: always
    env_file: ./.env.redis.sessions
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "8001:8001"
    networks:
      - into-net
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf


  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-server:7.2.1
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9997:9997"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka

volumes:
  redis_data:
  postgres_data:
